//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eschool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eschoolEntities : DbContext
    {
        public eschoolEntities()
            : base("name=eschoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_Classe> Student_Classe { get; set; }
        public virtual DbSet<Student_Filiere> Student_Filiere { get; set; }
        public virtual DbSet<Student_Infos> Student_Infos { get; set; }
    }
}
