//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eschool
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student_Infos
    {
        public int Student_Id { get; set; }
        [Display(Name = "First Name")]
        public string Student_Fname { get; set; }
        [Display(Name = "Last Name")]
        public string Student_Lname { get; set; }
        [Display(Name = "Age")]
        public Nullable<int> Student_Age { get; set; }
        [Display(Name = "Filiere")]
        public Nullable<int> Student_Filiere_Id { get; set; }
        [Display(Name = "Classe")]
        public Nullable<int> Student_Classe_Id { get; set; }
        [Display(Name = "N° Phone")]
        public string Student_Phone { get; set; }
        [Display(Name = "E-mail")]
        public string Student_Email { get; set; }
        [Display(Name = "Picture")]
        public byte[] Student_Photo { get; set; }
    
        public virtual Student_Classe Student_Classe { get; set; }
        public virtual Student_Filiere Student_Filiere { get; set; }
    }
}
